import{i as c,a as g,S as v}from"./assets/vendor-CjwUT-lV.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const t of s)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(s){const t={};return s.integrity&&(t.integrity=s.integrity),s.referrerPolicy&&(t.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?t.credentials="include":s.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(s){if(s.ep)return;s.ep=!0;const t=n(s);fetch(s.href,t)}})();const e={form:document.querySelector(".form"),gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),searchBtn:document.querySelector(".js-search-btn"),loadMoreBtn:document.querySelector(".js-laod-more-btn"),scrollToTopBtn:document.querySelector(".js-scroll-to-top-btn")},L=window.location.origin.includes("localhost")||window.location.origin.includes("127.0.0.1");c.settings({timeout:3e3,transitionIn:"flipInX",transitionOut:"flipOutX",iconColor:"#FFF",color:"#FFF",close:!0,position:"topRight",messageColor:"#FFF",messageSize:"16px",progressBar:!0,progressBarEasing:"linear",message:"Sorry, something went wrong.",iconUrl:L?"./public/img/illegal.svg":"/goit-advancedjs-hw-03/img/illegal.svg",progressBarColor:"#B51B1B",backgroundColor:"#EF4040",maxWidth:"432px"});const w="40358053-aa77a52d7b78d629a29aff12d",b="https://pixabay.com/api";g.defaults.baseURL=b;g.defaults.params={key:w,image_type:"photo",orientation:"horizontal",safesearch:"true"};const u=async o=>{const a={q:o.query,page:o.page,per_page:o.perPage},{data:n}=await g.get("/",{params:a});return n},B=new v(".gallery-link",{captionsData:"alt",captionDelay:250}),h=o=>{const a=({largeImageURL:r,webformatURL:s,tags:t,likes:i,views:m,comments:f,downloads:y})=>`
      <li class="card card-set-item">
            <a href="${r}" class="gallery-link" href="#">
              <div class="photo-box">
                <img
                  src="${s}"
                  alt="${t}"
                  class="photo"
                />
              </div>
              <div class="capture">
                <div class="item"><span class="accent">Likes</span>${i}</div>
                <div class="item"><span class="accent">Views</span>${m}</div>
                <div class="item"><span class="accent">Comments</span>${f}</div>
                <div class="item">
                  <span class="accent">Downloads</span>${y}
                </div>
              </div>
            </a>
          </li>
      `,n=o.map(r=>a(r)).join("");e.gallery.insertAdjacentHTML("beforeend",n),B.refresh()},l={page:1,perPage:15,query:""},d={scrollY:0},S=2,M=o=>{o.preventDefault(),e.gallery.innerHTML="",e.loadMoreBtn.classList.add("visually-hidden");const a=e.form.elements.search,n=a.value.trim();if(l.query=n,l.page=1,a.value="",n===""){c.show({message:"Oops! Looks like you forgot to enter something."});return}e.loader.classList.remove("hidden"),e.searchBtn.disabled=!0,u(l).then(r=>{if(r.hits.length===0){c.show({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(r.hits);const s=document.querySelector(".card"),t=Math.ceil(s.getBoundingClientRect().height);d.scrollY=t*S,l.page*l.perPage<r.totalHits&&(e.loadMoreBtn.classList.remove("visually-hidden"),e.loadMoreBtn.disabled=!1,e.loadMoreBtn.addEventListener("click",p))}).catch(r=>c.show({message:`Sorry, something went wrong.: ${r}`})).finally(()=>{e.loader.classList.add("hidden"),e.searchBtn.disabled=!1})},p=()=>{e.loader.classList.remove("hidden"),e.loadMoreBtn.disabled=!0,l.page+=1,u(l).then(o=>{h(o.hits),window.scrollBy({top:d.scrollY,behavior:"smooth"}),l.page*l.perPage<o.totalHits||(e.loadMoreBtn.classList.add("visually-hidden"),e.loadMoreBtn.removeEventListener("click",p),c.show({backgroundColor:"#FFA000",message:"We're sorry, but you've reached the end of search results."}))}).catch(o=>c.show({message:`Sorry, something went wrong.: ${o}`})).finally(()=>{e.loader.classList.add("hidden"),e.loadMoreBtn.disabled=!1})};e.form.addEventListener("submit",M);window.addEventListener("scroll",()=>{const o=d.scrollY>0?d.scrollY-1:window.innerHeight/3;window.scrollY>o?e.scrollToTopBtn.classList.remove("invisible"):e.scrollToTopBtn.classList.add("invisible")});e.scrollToTopBtn.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
